title: Your awesome title
email: your-email@domain.com
description: Hi
baseurl: ""
url: "http://salmendo.com"

markdown: kramdown

exclude: [Gemfile, Gemfile.lock, scss, assets/scss, assets/libs]

assets:
  css: assets/css/
  svg: assets/svg/
  img: assets/img/
  js: assets/js/

sass:
  sass_dir: assets/scss
  style: :compressed